### ISSUE TITLE
YSI data availability

### ISSUE THREAD

**Issue by jessegmeyerlab** [NREL/nfp#20]
Can you please share the YSI example data referenced in the example nb? I can't find the table in the referenced publication. The paper text refers to the supplemental but there is none linked? I'm trying to understand what shape I need to put my data into. Thanks in advance for any help.

**Comment by pstjohn** [comment]
Whoops, sorry about that; the most up-to-date version of that data is available here:
https://github.com/pstjohn/YSIs_for_prediction/

I apologies the documentation for the library isn't in better shape! Please don't hesitate to reach out with any questions. I re-ran that notebook to make sure everything still works with tf 2.8.0, and inlcuded a link to that YSI repository
